// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification = "<Pending>", Scope = "member", Target = "~M:InventoryManagement.API.Controllers.GroupController.GetGroups(System.Int32)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.IActionResult}")]
[assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification = "<Pending>", Scope = "member", Target = "~M:InventoryManagement.API.Controllers.GroupController.GetGroupCollection(System.Int32,System.Int32,System.Int32)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.IActionResult}")]
[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:InventoryManagement.API.Controllers.GroupController.GetGroups(System.Int32)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.IActionResult}")]
[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:InventoryManagement.API.Controllers.GroupController.GetGroupCollection(System.Int32,System.Int32,System.Int32)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.IActionResult}")]
[assembly: SuppressMessage("Design", "CA1052:Static holder types should be Static or NotInheritable", Justification = "<Pending>", Scope = "type", Target = "~T:InventoryManagement.API.Program")]
[assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification = "<Pending>", Scope = "member", Target = "~M:InventoryManagement.API.Managers.GroupManager.GetGroupCollection(System.Int32,System.Int32,System.Int32)~System.Threading.Tasks.Task{InventoryManagement.API.Models.RequestResponse{System.Collections.Generic.List{InventoryManagement.API.Models.Group}}}")]
[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:InventoryManagement.API.Managers.GroupManager.GetGroupCollection(System.Int32,System.Int32,System.Int32)~System.Threading.Tasks.Task{InventoryManagement.API.Models.RequestResponse{System.Collections.Generic.List{InventoryManagement.API.Models.Group}}}")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:InventoryManagement.API.Models.RequestResponse`1.Convert``1(System.Converter{`0,``0})~InventoryManagement.API.Models.RequestResponse{``0}")]
[assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification = "<Pending>", Scope = "member", Target = "~M:InventoryManagement.API.Managers.GroupManager.GetGroups(System.Int32)~System.Threading.Tasks.Task{InventoryManagement.API.Models.RequestResponse{System.Collections.Generic.List{InventoryManagement.API.Models.Group}}}")]
[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:InventoryManagement.API.Managers.GroupManager.GetGroups(System.Int32)~System.Threading.Tasks.Task{InventoryManagement.API.Models.RequestResponse{System.Collections.Generic.List{InventoryManagement.API.Models.Group}}}")]
[assembly: SuppressMessage("Usage", "CA2227:Collection properties should be read only", Justification = "<Pending>", Scope = "member", Target = "~P:InventoryManagement.API.Models.UserProfile.Subscriptions")]
[assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification = "<Pending>", Scope = "member", Target = "~M:InventoryManagement.API.Controllers.GroupController.UpsertGroup(InventoryManagement.API.Models.Group)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.IActionResult}")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:InventoryManagement.API.Controllers.GroupController.UpsertGroup(InventoryManagement.API.Models.Group)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.IActionResult}")]
[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:InventoryManagement.API.Controllers.GroupController.UpsertGroup(InventoryManagement.API.Models.Group)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.IActionResult}")]
[assembly: SuppressMessage("Minor Code Smell", "S1450:Private fields only used as local variables in methods should become local variables", Justification = "<Pending>", Scope = "member", Target = "~F:InventoryManagement.API.Startup._configuration")]
